### ISSUE TITLE
Scripts don't handle tags with dashes any more

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/DebianPackagingScripts#20]
Some projects like the open62541-interface have a tag syntax with a dash, because they have to contain the software version of the target packages, plus changes in the interface project. (e.g. 1.2.1-2). This used to work, but is broken lately.

The packaging scripts should support this and be fixed.

**Comment by zenker** [comment]
Sorry Martin, but this works for me!
There is a different problem with the interface package...
I will fix that soon and once that's done you can convince your self that it is working.
